CREATE SCHEMA IF NOT EXISTS "bday";

CREATE TYPE "bday"."CalendarType" AS ENUM ('SOLAR', 'LUNAR');
CREATE TYPE "bday"."ChannelKind" AS ENUM ('WECOM_BOT', 'EMAIL');
CREATE TYPE "bday"."DeliveryStatus" AS ENUM ('PENDING', 'SENT', 'FAILED', 'SKIPPED');

CREATE TABLE "bday"."person" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(80) NOT NULL,
  "relation" VARCHAR(40),
  "calendar" "bday"."CalendarType" NOT NULL DEFAULT 'SOLAR',
  "birth_year" SMALLINT,
  "birth_month" SMALLINT NOT NULL CHECK ("birth_month" BETWEEN 1 AND 12),
  "birth_day" SMALLINT NOT NULL CHECK ("birth_day" BETWEEN 1 AND 31),
  "is_leap_month" BOOLEAN NOT NULL DEFAULT false,
  "note" TEXT,
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "person_lunar_leap_check" CHECK (NOT "is_leap_month" OR "calendar" = 'LUNAR')
);

CREATE TABLE "bday"."reminder_rule" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" BIGINT,
  "days_before" SMALLINT NOT NULL CHECK ("days_before" BETWEEN 0 AND 366),
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "reminder_rule_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "bday"."person"("id") ON DELETE CASCADE
);

CREATE TABLE "bday"."notification_channel" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR(80) NOT NULL,
  "kind" "bday"."ChannelKind" NOT NULL,
  "destination" VARCHAR(320),
  "secret_ref" VARCHAR(120),
  "enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "bday"."notification_delivery" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "person_id" BIGINT NOT NULL,
  "rule_id" BIGINT NOT NULL,
  "channel_id" BIGINT NOT NULL,
  "birthday_on" DATE NOT NULL,
  "scheduled_for" DATE NOT NULL,
  "days_before" SMALLINT NOT NULL,
  "status" "bday"."DeliveryStatus" NOT NULL DEFAULT 'PENDING',
  "message" TEXT NOT NULL,
  "error" TEXT,
  "sent_at" TIMESTAMPTZ(3),
  "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "notification_delivery_person_id_fkey" FOREIGN KEY ("person_id") REFERENCES "bday"."person"("id") ON DELETE RESTRICT,
  CONSTRAINT "notification_delivery_rule_id_fkey" FOREIGN KEY ("rule_id") REFERENCES "bday"."reminder_rule"("id") ON DELETE RESTRICT,
  CONSTRAINT "notification_delivery_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "bday"."notification_channel"("id") ON DELETE RESTRICT,
  CONSTRAINT "notification_delivery_identity_key" UNIQUE ("person_id", "rule_id", "channel_id", "birthday_on")
);

CREATE UNIQUE INDEX "reminder_rule_global_days_key"
  ON "bday"."reminder_rule" ("days_before") WHERE "person_id" IS NULL;
CREATE UNIQUE INDEX "reminder_rule_person_days_key"
  ON "bday"."reminder_rule" ("person_id", "days_before") WHERE "person_id" IS NOT NULL;
CREATE INDEX "person_enabled_idx" ON "bday"."person" ("enabled");
CREATE INDEX "reminder_rule_person_id_idx" ON "bday"."reminder_rule" ("person_id");
CREATE INDEX "reminder_rule_enabled_days_before_idx" ON "bday"."reminder_rule" ("enabled", "days_before");
CREATE INDEX "notification_channel_enabled_idx" ON "bday"."notification_channel" ("enabled");
CREATE INDEX "notification_delivery_schedule_status_idx" ON "bday"."notification_delivery" ("scheduled_for", "status");
CREATE INDEX "notification_delivery_person_id_idx" ON "bday"."notification_delivery" ("person_id");
CREATE INDEX "notification_delivery_rule_id_idx" ON "bday"."notification_delivery" ("rule_id");
CREATE INDEX "notification_delivery_channel_id_idx" ON "bday"."notification_delivery" ("channel_id");
